# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c50c37bf8ae62d6810c478a45d9a84294ecafe46999c4c09cd4f53dd74f7d8073a0496e13c2e91bd08c3d9152d9a4fa86d46bfa8929084295aa7c7a708f1595

test:
  secret_key_base: 0a25a3a65006da6a1f38b17c400ea916f956bed40638b2eaccadd4a01f89e3277b5669dfd4bbff3788d58c21409e831a1daf47ae071c5bd511b38c7caff7541b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
